export const SEARCH_FOCUS = 'header/SEARCH_FOCUS';
export const SEARCH_BLUR = 'header/SEARCH_BLUR';
export const CHANGE_LIST ='header/CHANGE_LIST';
export const MOUSE_ENTER = 'header/MOUSE_ENTER';
export const MOUSE_LEAVE = 'header/MOUSE_LEAVE';
export const CHANGE_PAGE = 'header/CHANGE_PAGE';
export const SHOW_MENU = 'header/SHOW_MENU';
export const SHOW_SIDE_MENU = 'header/SHOW_SIDE_MENU';
export const HIDE_SIDE_MENU = 'header/HIDE_SIDE_MENU';
